### ISSUE TITLE
Feature request: use log crate

### ISSUE THREAD

**Issue by yu-re-ka** [wladwm/zettabgp#5]
Currently there are many println or eprintln statements in the code, which can be confusing to users of an application using the zettabgp library.
It would be wonderful if these could be switched to `log::info!` and `log::warn!` statements, which can be filtered by the application.
If you like this idea, I could prepare a PR.

**Comment by wladwm** [comment]
Great idea!

**Comment by yu-re-ka** [comment]
Thanks.

For the record these are all the changes I had queued so far, in case you want to make another release on crates.io
